In [1]:
import numpy as np
from time import time

### Q1 : Fun with arrays

In [2]:
# A1
arr = np.arange(1,16).reshape(3,5).T
print("arr = ", arr)

arr =  [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [3]:
# A2
arr2 = arr[1:4][0:3:2]
arr2

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [4]:
# B
arr3 = np.ones(25).reshape(5,5)
arr3[1:-1,1:-1] = 0
arr3

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
def standard_deviation(a):
    a_average = np.average(a)
    a_sum_over_squares = np.sum((a-a_average)**2)
    a_sos_norm = a_sum_over_squares/a.size
    std = np.sqrt(a_sos_norm)
    return std

In [6]:
a = np.arange(200_000_000)

In [7]:
t0 = time()
sigma = standard_deviation(a)
t1 = time()

print(f"sigma = {sigma}, time elapsed: {t1-t0}")

sigma = 57735026.918975495, time elapsed: 12.822670459747314


In [8]:
t2 = time()
sigma_np = np.std(a)
t3 = time()

print(f"sigma (numpy) = {sigma_np}, time elapsed: {t3-t2}")

sigma (numpy) = 57735026.918975495, time elapsed: 4.908119201660156


In [9]:
A = np.arange(1,19,2)#.reshape(3,3)
B = np.arange(0,18,2)#.reshape(3,3)

A, B

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16]))

In [10]:
A_inner_B_np = np.inner(A,B)
A_inner_B = np.einsum('i,i',A,B)

A_inner_B_np, A_inner_B

(888, 888)

In [11]:
C = np.arange(1,19,2).reshape(3,3)
D = np.arange(0,18,2).reshape(3,3)

C, D

(array([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]),
 array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

In [12]:
# element-wise multiplication
np.einsum('ij,ij->ij',C,D)

array([[  0,   6,  20],
       [ 42,  72, 110],
       [156, 210, 272]])

### Q6 : Conway's Game of Life

In [26]:
grid_size = 400
grid_shape = (20,20)
max_num_gens = 1000

In [27]:
rng = np.random.default_rng(1984)

# initial conditions
grid = np.zeros(grid_size, dtype=int).reshape(grid_shape)
grid[1:-1,1:-1] = rng.integers(low=0, high=2, size=(18, 18))

#print(grid)

In [28]:
# routine for one step of evolution
def gol_step(grid):
    # exclude boundary from computation
    table = grid[1:-1, 1:-1]

    # compute number of live neighbours
    up_count = grid[:-2, :-2] + grid[:-2, 1:-1] + grid[:-2, 2:]
    down_count = grid[2:, :-2] + grid[2:, 1:-1] + grid[2:, 2:]
    side_count = grid[1:-1, :-2] + grid[1:-1, 2:]
    neigh_live_count = up_count + down_count + side_count
    
    # gol rules application
    stay_alive = (table == 1) & ((neigh_live_count == 2) | (neigh_live_count == 3))
    come_alive = (table == 0) & (neigh_live_count == 3)
    new_table = (stay_alive | come_alive).astype(int)

    # result of single step evolution
    grid[1:-1, 1:-1] = new_table

    return grid

In [29]:
grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 1,

In [30]:
gol_step(grid)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1,